apps/friends/urls.py
from django.conf.urls import url
from . import views

app_name = 'friends'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^remove$', views.remove, name='remove'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    # url(r'^getItem/(?P<id>\d+)$', views.getItem, name='getItem'),
]

apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_reg'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register, name='register'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login_reg/', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^friends/', include('apps.friends.urls', namespace='friends')),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
]

apps/friends/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_reg.models import User
from datetime import datetime, date

# Create your models here.
class FriendManager(models.Manager):
    def create(self, id):
        friend = User.objects.get(id=id)
        print (friend.id, friend.name)
        this_friend = Friend.objects.create(friend=friend)
        print (this_friend.id, this_friend.friend.id, this_friend.friend.name)
        return (True, this_friend.id)

    def bridge_connections(self, postData):
        if not postData:
            return (False)
        else:
            user = User.objects.get(id=int(postData['user']))
            # print ('USER:', user.id, user.name, user.alias)
            friend = Friend.objects.get(id=int(postData['friend']))
            # print ('FRIEND:', friend.id, friend.name, friend.alias)

            Friendship.objects.create(user=user, friend=friend)
            return (True)


    def delete(self, postData):
        friendship = Friendship.objects.get(id=int(postData['friendship']))
        friendship.delete()
        return True


class Friend(models.Model):
    friend = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_table_id', default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    friendManager = FriendManager()
    objects = models.Manager()

class Friendship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/friends/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, Friend, Friendship

# Create your views here.
def index(request):
    # Friendship.objects.all().delete()
    # this = Friend.objects.filter(id=10)
    # this.delete()
    id = request.session['thisUser']
    # print(id)
    context = {
    'users':User.objects.all(),
    'thisUser':User.objects.get(id=id),
    'friends':Friend.objects.all(),
    'friendships':Friendship.objects.all(),
    }
    if ('newUser' in request.session) == True:
        # print ('new registration')
        verify = Friend.friendManager.create(id)
        if verify[0] == True:
            # print ('added to friend table')
            del request.session['newUser']
            request.session.modified = True
            return render(request, 'friends/index.html', context)
    else:
        # print ('already registered')
        return render(request, 'friends/index.html', context)

def add(request):
    if request.method == "POST":
        verify = Friend.friendManager.bridge_connections(request.POST)

        if verify == True:
            # print ('friendship created')
            return redirect(reverse('friends:index'))
        else:
            print ('something went wrong')
            return redirect(reverse('friends:index'))

def show(request, id):
    if request.method == "GET":
        context = {
            'user':User.objects.get(id=id)
        }
        return render(request, 'friends/show.html', context)

def remove(request):
    if request.method == "POST":
        destroy = Friend.friendManager.delete(request.POST)
        if destroy == True:
            return redirect(reverse('friends:index'))

apps/friends/templates/friends/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Friends</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, travel">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <nav>
        <a class="btn btn-link" href="{% url 'login_reg:logout' %}" role="button">Logout</a>
      </nav>
      <header class="page-header">
        <h1>Friends List <small>{% if request.session.success %}
          Welcome {{ request.session.success }}
        {% endif %}</small></h1>
      </header>

      <!-- {{ thisUser.id }} {{ thisUser.name }} -->
  <!-- your Friends List section -->
      <section>
        <h4>Here is your list of friends:</h4>
        <table class="table table-bordered">
          <thead>
            <th>Alias</th>
            <th>Action</th>
          </thead>

          <tbody>
            {% for friendship in friendships %}
              {% if friendship.user.id == thisUser.id %}
                <tr>
                  <td>{{ friendship.friend.friend.alias }}</td>
                  <td>
                    <form action="{% url 'friends:remove' %}" method="POST">
                    {% csrf_token %}
                      <a class="btn btn-link" href="{% url 'friends:show' friendship.friend.friend.id %}">View Profile</a>
                      <input type="hidden" name="friendship" value="{{ friendship.id }}">
                      <input class="btn btn-link" type="submit" value="Remove as Friend">
                    </form>
                  </td>
                </tr>
              {% elif friendship.friend.id == thisUser.id %}
                <tr>
                  <td>{{ friendship.user.alias }}</td>
                  <td>
                    <form action="{% url 'friends:remove' %}" method="POST">
                    {% csrf_token %}
                      <a class="btn btn-link" href="{% url 'friends:show' friendship.user.id %}">View Profile</a>
                      <input type="hidden" name="friendship" value="{{ friendship.id }}">
                      <input class="btn btn-link" type="submit" value="Remove as Friend">
                    </form>
                  </td>
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </section>

  <!-- other people section -->
      <section>
        <h4>Other users not on your friends list:</h4>
        <table class="table table-bordered">
          <thead>
            <th>Alias</th>
            <th>Action</th>
          </thead>

          <tbody>
            {% for friend in friends %}
              {% if friend.friend != thisUser %}
                {% if friend.friendship.user != thisUser %}
                    <tr>
                      <td><a href="{% url 'friends:show' friend.id %}">{{ friend.friend.alias }}</a></td>
                      <td>
                        <form action="{% url 'friends:add' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="user" value="{{ thisUser.id }}">
                          <input type="hidden" name="friend" value="{{ friend.id }}">
                          <input class="btn btn-link" type="submit" value="Add as Friend">
                        </form>
                      </td>
                    </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </section>
      <!-- {% for friendship in friendships %}
        <p>friendship:{{ friendship.id }} | friendid:{{ friendship.friend.id }} |  frndusrid:{{ friendship.friend.user.id }} | frname: {{ friendship.friend.friend.name }} | userid:{{ friendship.user.id }} | username: {{ friendship.user.name }}</p>
      {% endfor %} -->
    </div>
  </body>
</html>

apps/friends/templates/friends/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Friends</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, travel">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <nav>
        <a class="btn btn-link" href="{% url 'login_reg:logout' %}" role="button">Logout</a>
        <a class="btn btn-link" href="{% url 'friends:index' %}" role="button">Home</a>
      </nav>
      <header class="page-header">
        <h1>{{ user.alias }}'s Profile</h1>
      </header>

      {{ thisUser.id }} {{ thisUser.name }}

      <section>
        <h4>Name: {{ user.name }}</h4>
        <h4>Email Address: {{ user.email }}</h4>
      </section>
    </div>
  </body>
</html>