apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_reg'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register, name='register'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login_reg/', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^friends/', include('apps.friends.urls', namespace='friends')),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
]

apps/login_reg/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime, date
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.
class UserManager(models.Manager):
    def login(self, postData):
        email = postData['email']
        password = postData['password']

        alerts = []

        if len(email) < 1:
            alerts.append('Please enter email address.')
        try:
            user = User.objects.get(email=email)
        except:
            print ('Email NOT REGISTERED')
            alerts.append('The email "{}" is either incorrect or has not been registered.'.format(email))
            return (False, alerts)
        else:
            if email == user.email:
                if bcrypt.hashpw(password.encode(), user.pw_hashed.encode()) == user.pw_hashed:
                    # print ('it matches', user.id)
                    return (True, 'back, {}!'.format(user.name), user.id)
                else:
                    # print ('no pw match')
                    alerts.append('The password entered is incorrect. Please try again.')

            if alerts:
                return (False, alerts)


    def register(self, postData):
        # grabs user input from registration form
        name = postData['name']
        alias = postData['alias']
        email = postData['email']
        dob = postData['dob']
        password = postData['password']
        pw_verify = postData['pw_verify']

        alerts = []

        if len(postData['name']) < 1:
            alerts.append('Name cannot be left blank.')

        if len(postData['alias']) < 1:
            alerts.append('Alias cannot be left blank.')

        if len(postData['email']) < 1:
            alerts.append('Email cannot be left blank.')
        elif not EMAIL_REGEX.match(email):
            alerts.append('Invalid email address.')

        if len(password) < 8:
            alerts.append('Password must be at least 8 characters in length.')
        elif password != pw_verify:
            alerts.append('Passwords do not match.')

        if len(postData['dob']) < 1:
            alerts.append('Date of birth cannot be left blank.')
        else:
            dob = datetime.strptime(postData['dob'], '%Y-%m-%d')
            if dob > datetime.today():
                print ('DOB IN FUTURE')
                alerts.append('Date of birth cannot be in the future.')

        if alerts:
            return (False, alerts)
        # else:
        #     try:
        #         User.objects.get(name=name)
        #     except:
        #         print ('USER ALREADY EXISTS')
        #         alerts.append('The name "{}" has already been registered.'.format(name))
        #         return (False, alerts)
        else:
            pw_hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            user = User.objects.create(name=name, alias=alias, email=email, dob=postData['dob'], pw_hashed=pw_hashed)
            return (True, 'aboard, {}!'.format(name), user.id)


class User(models.Model):
    name = models.CharField(max_length=255, default=1)
    alias = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    dob = models.DateField(auto_now=False)
    pw_hashed = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    userManager = UserManager()
    objects = models.Manager()

apps/login_reg/views.py
# login_reg
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from ..friends.models import Friend
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    # User.objects.all().delete()
    # Friend.objects.all().delete
    context = {
        'users':User.objects.all()
    }
    return render(request, 'login_reg/index.html', context)


def login(request):
    if request.method == "POST":
        verify = User.userManager.login(request.POST)

        if verify[0] == False:
            for alert in verify[1]:
                messages.add_message(request, messages.INFO, alert)
            return redirect(reverse('login_reg:index'))

        elif verify[0] == True:
            request.session['success'] = verify[1]
            request.session['thisUser'] = verify[2]
            return redirect(reverse('friends:index'))

        else:
            request.session.clear()
            return redirect(reverse('login_reg:index'))


def register(request):
    if request.method == "POST":
        verify = User.userManager.register(request.POST)

        if verify[0] == False:
            for alert in verify[1]:
                messages.add_message(request, messages.INFO, alert)
            return redirect(reverse('login_reg:index'))

        elif verify[0] == True:
            request.session['success'] = verify[1]
            request.session['thisUser'] = verify[2]
            request.session['newUser'] = verify[2]
            return redirect(reverse('friends:index'))
        else:
            request.session.clear()
            return redirect(reverse('login_reg:index'))


def logout(request):
    request.session.clear()
    return redirect(reverse('login_reg:index'))

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Login and Registration</title>
    <meta name="description" content="Coding Dojo, Python II, Django II, Friends">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <header class="page-header">
        <h1>Friends <small> Login and Registration</small></h1>
      </header>

  <!-- flash messages section -->
      <section>
        {% if messages %}
          <div class="alert alert-danger">
            {% for alert in messages %}
              <p {% if messages.tags %} class="messages.tags" {% endif %}>{{ alert }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </section>

  <!-- forms section -->
      <section>
        <article>
          <h3 class="login_reg">Register</h3>
          <form class="form-horizontal" action="{% url 'login_reg:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label">Name:</label>
              <input class="form-control" type="text" name="name">
            </div>
            <div class="form-group">
              <label class="control-label">Alias:</label>
              <input class="form-control" type="text" name="alias">
            </div>
            <div class="form-group">
              <label class="control-label">Email:</label>
              <input class="form-control" type="text" name="email">
            </div>
            <div class="form-group">
              <label class="control-label">Password:</label>
              <input class="form-control" type="text" name="password">
            </div>
            <div class="form-group">
              <label class="control-label">Confirm pw:</label>
              <input class="form-control" type="text" name="pw_verify">
            </div>
            <div class="form-group">
              <label class="control-label">Date of Birth:</label>
              <input class="form-control" style="width:auto;" type="date" name="dob">
            </div>
            <div class="form-group">
              <input class="btn btn-primary" type="submit" value="Register">
            </div>
          </form>
        </article>

        <article>
          <h3 class="login_reg">Login</h3>
          <form class="form-horizontal" action="{% url 'login_reg:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label">Email:</label>
              <input class="form-control" type="text" name="email">
            </div>
            <div class="form-group">
              <label class="control-label">Password:</label>
              <input class="form-control" type="text" name="password">
            </div>
            <div class="form-group">
              <input class="btn btn-primary" type="submit" value="Login">
            </div>
          </form>
        </article>
      </section>

    </div>
  </body>
</html>